# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SystemStationMainWindowWUIyBW.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QStackedWidget, QWidget)

class Ui_System_Station_Main_window(object):
    def setupUi(self, System_Station_Main_window):
        if not System_Station_Main_window.objectName():
            System_Station_Main_window.setObjectName(u"System_Station_Main_window")
        System_Station_Main_window.resize(800, 480)
        System_Station_Main_window.setMinimumSize(QSize(800, 480))
        self.main_stackedWidget = QStackedWidget(System_Station_Main_window)
        self.main_stackedWidget.setObjectName(u"main_stackedWidget")
        self.main_stackedWidget.setGeometry(QRect(0, 0, 800, 480))
        self.main_stackedWidget.setStyleSheet(u"border: 1px Solid black;")
        self.Main_page = QWidget()
        self.Main_page.setObjectName(u"Main_page")
        self.label_12 = QLabel(self.Main_page)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(390, 360, 71, 71))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(16)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.Main_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 320, 151, 31))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(11)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label = QLabel(self.Main_page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(616, 0, 181, 40))
        self.label.setFont(font)
        self.go_to_main_settings_pushButton = QPushButton(self.Main_page)
        self.go_to_main_settings_pushButton.setObjectName(u"go_to_main_settings_pushButton")
        self.go_to_main_settings_pushButton.setGeometry(QRect(0, 0, 135, 40))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(14)
        font2.setBold(True)
        self.go_to_main_settings_pushButton.setFont(font2)
        self.label_8 = QLabel(self.Main_page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(290, 360, 71, 71))
        self.label_8.setFont(font)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.stackedWidget = QStackedWidget(self.Main_page)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 40, 801, 281))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.main_first_pushButton = QPushButton(self.Main_page)
        self.main_first_pushButton.setObjectName(u"main_first_pushButton")
        self.main_first_pushButton.setGeometry(QRect(140, 0, 41, 40))
        self.label_10 = QLabel(self.Main_page)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(590, 360, 71, 71))
        self.label_10.setFont(font)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.Main_page)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(690, 360, 71, 71))
        self.label_11.setFont(font)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.Main_page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 350, 151, 31))
        self.label_3.setFont(font1)
        self.label_6 = QLabel(self.Main_page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 440, 151, 31))
        self.label_6.setFont(font1)
        self.label_9 = QLabel(self.Main_page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(490, 360, 71, 71))
        self.label_9.setFont(font)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.Main_page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 380, 151, 31))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.Main_page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 410, 151, 31))
        self.label_5.setFont(font1)
        self.label_7 = QLabel(self.Main_page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 360, 71, 71))
        self.label_7.setFont(font)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.main_third_pushButton = QPushButton(self.Main_page)
        self.main_third_pushButton.setObjectName(u"main_third_pushButton")
        self.main_third_pushButton.setGeometry(QRect(240, 0, 41, 40))
        self.main_second_pushButton = QPushButton(self.Main_page)
        self.main_second_pushButton.setObjectName(u"main_second_pushButton")
        self.main_second_pushButton.setGeometry(QRect(190, 0, 41, 40))
        self.main_stackedWidget.addWidget(self.Main_page)
        self.Settings_Main_page = QWidget()
        self.Settings_Main_page.setObjectName(u"Settings_Main_page")
        self.go_to_main_page_pushButton = QPushButton(self.Settings_Main_page)
        self.go_to_main_page_pushButton.setObjectName(u"go_to_main_page_pushButton")
        self.go_to_main_page_pushButton.setGeometry(QRect(50, 0, 130, 50))
        self.go_to_main_page_pushButton.setFont(font1)
        self.go_to_main_page_label = QLabel(self.Settings_Main_page)
        self.go_to_main_page_label.setObjectName(u"go_to_main_page_label")
        self.go_to_main_page_label.setGeometry(QRect(0, 0, 50, 50))
        self.settings_buttons_stackedWidget = QStackedWidget(self.Settings_Main_page)
        self.settings_buttons_stackedWidget.setObjectName(u"settings_buttons_stackedWidget")
        self.settings_buttons_stackedWidget.setGeometry(QRect(0, 60, 182, 418))
        self.Settings_Main_Buttons_page = QWidget()
        self.Settings_Main_Buttons_page.setObjectName(u"Settings_Main_Buttons_page")
        self.go_to_manager_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_manager_page_label.setObjectName(u"go_to_manager_page_label")
        self.go_to_manager_page_label.setGeometry(QRect(0, 0, 40, 50))
        self.go_to_manager_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_manager_page_pushButton.setObjectName(u"go_to_manager_page_pushButton")
        self.go_to_manager_page_pushButton.setGeometry(QRect(40, 0, 110, 50))
        self.go_to_manager_page_pushButton.setFont(font1)
        self.go_to_tracking_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_tracking_page_label.setObjectName(u"go_to_tracking_page_label")
        self.go_to_tracking_page_label.setGeometry(QRect(0, 60, 40, 50))
        self.go_to_tracking_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_tracking_page_pushButton.setObjectName(u"go_to_tracking_page_pushButton")
        self.go_to_tracking_page_pushButton.setGeometry(QRect(40, 60, 100, 50))
        self.go_to_tracking_page_pushButton.setFont(font1)
        self.go_to_journal_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_journal_page_label.setObjectName(u"go_to_journal_page_label")
        self.go_to_journal_page_label.setGeometry(QRect(0, 120, 40, 50))
        self.go_to_journal_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_journal_page_pushButton.setObjectName(u"go_to_journal_page_pushButton")
        self.go_to_journal_page_pushButton.setGeometry(QRect(40, 120, 100, 50))
        self.go_to_journal_page_pushButton.setFont(font1)
        self.go_to_station_settings_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_station_settings_page_label.setObjectName(u"go_to_station_settings_page_label")
        self.go_to_station_settings_page_label.setGeometry(QRect(0, 180, 40, 50))
        self.go_to_station_settings_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_station_settings_page_pushButton.setObjectName(u"go_to_station_settings_page_pushButton")
        self.go_to_station_settings_page_pushButton.setGeometry(QRect(40, 180, 100, 50))
        self.go_to_station_settings_page_pushButton.setFont(font1)
        self.go_to_engineering_menu_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_engineering_menu_page_label.setObjectName(u"go_to_engineering_menu_page_label")
        self.go_to_engineering_menu_page_label.setGeometry(QRect(0, 240, 40, 50))
        self.go_to_engineering_menu_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_engineering_menu_page_pushButton.setObjectName(u"go_to_engineering_menu_page_pushButton")
        self.go_to_engineering_menu_page_pushButton.setGeometry(QRect(40, 240, 100, 50))
        self.go_to_engineering_menu_page_pushButton.setFont(font1)
        self.go_to_panel_settings_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_panel_settings_page_label.setObjectName(u"go_to_panel_settings_page_label")
        self.go_to_panel_settings_page_label.setGeometry(QRect(0, 300, 40, 50))
        self.go_to_panel_settings_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_panel_settings_page_pushButton.setObjectName(u"go_to_panel_settings_page_pushButton")
        self.go_to_panel_settings_page_pushButton.setGeometry(QRect(40, 300, 110, 50))
        self.go_to_panel_settings_page_pushButton.setFont(font1)
        self.go_to_contacts_page_label = QLabel(self.Settings_Main_Buttons_page)
        self.go_to_contacts_page_label.setObjectName(u"go_to_contacts_page_label")
        self.go_to_contacts_page_label.setGeometry(QRect(0, 360, 40, 50))
        self.go_to_contacts_page_pushButton = QPushButton(self.Settings_Main_Buttons_page)
        self.go_to_contacts_page_pushButton.setObjectName(u"go_to_contacts_page_pushButton")
        self.go_to_contacts_page_pushButton.setGeometry(QRect(40, 360, 110, 50))
        self.go_to_contacts_page_pushButton.setFont(font1)
        self.go_to_contacts_page_pushButton.setLayoutDirection(Qt.LeftToRight)
        self.label_21 = QLabel(self.Settings_Main_Buttons_page)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(150, 360, 30, 50))
        self.label_22 = QLabel(self.Settings_Main_Buttons_page)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(150, 300, 30, 50))
        self.label_23 = QLabel(self.Settings_Main_Buttons_page)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(140, 240, 40, 50))
        self.label_24 = QLabel(self.Settings_Main_Buttons_page)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(140, 180, 40, 50))
        self.label_25 = QLabel(self.Settings_Main_Buttons_page)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(140, 120, 40, 50))
        self.label_26 = QLabel(self.Settings_Main_Buttons_page)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(140, 60, 40, 50))
        self.settings_buttons_stackedWidget.addWidget(self.Settings_Main_Buttons_page)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.settings_buttons_stackedWidget.addWidget(self.page_7)
        self.settings_pages_stackedWidget = QStackedWidget(self.Settings_Main_page)
        self.settings_pages_stackedWidget.setObjectName(u"settings_pages_stackedWidget")
        self.settings_pages_stackedWidget.setGeometry(QRect(180, 0, 618, 478))
        self.Settings_Manager_page = QWidget()
        self.Settings_Manager_page.setObjectName(u"Settings_Manager_page")
        self.label_27 = QLabel(self.Settings_Manager_page)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(480, 0, 141, 31))
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(9)
        font3.setBold(True)
        self.label_27.setFont(font3)
        self.label_27.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line = QFrame(self.Settings_Manager_page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 80, 601, 2))
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line_2 = QFrame(self.Settings_Manager_page)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 130, 601, 2))
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.label_28 = QLabel(self.Settings_Manager_page)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 30, 40, 50))
        self.label_29 = QLabel(self.Settings_Manager_page)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 80, 40, 50))
        self.label_30 = QLabel(self.Settings_Manager_page)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 130, 40, 50))
        self.line_3 = QFrame(self.Settings_Manager_page)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 180, 601, 2))
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.label_31 = QLabel(self.Settings_Manager_page)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(50, 40, 200, 30))
        self.label_31.setFont(font1)
        self.label_32 = QLabel(self.Settings_Manager_page)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(50, 90, 200, 30))
        self.label_32.setFont(font1)
        self.label_33 = QLabel(self.Settings_Manager_page)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(50, 140, 191, 30))
        self.label_33.setFont(font1)
        self.shield_2_label = QLabel(self.Settings_Manager_page)
        self.shield_2_label.setObjectName(u"shield_2_label")
        self.shield_2_label.setGeometry(QRect(250, 130, 40, 50))
        self.monday_pushButton = QPushButton(self.Settings_Manager_page)
        self.monday_pushButton.setObjectName(u"monday_pushButton")
        self.monday_pushButton.setGeometry(QRect(295, 135, 40, 40))
        self.monday_pushButton.setFont(font1)
        self.tuesday_pushButton = QPushButton(self.Settings_Manager_page)
        self.tuesday_pushButton.setObjectName(u"tuesday_pushButton")
        self.tuesday_pushButton.setGeometry(QRect(340, 135, 40, 40))
        self.tuesday_pushButton.setFont(font1)
        self.wednesday_pushButton = QPushButton(self.Settings_Manager_page)
        self.wednesday_pushButton.setObjectName(u"wednesday_pushButton")
        self.wednesday_pushButton.setGeometry(QRect(385, 135, 40, 40))
        self.wednesday_pushButton.setFont(font1)
        self.thursday_pushButton = QPushButton(self.Settings_Manager_page)
        self.thursday_pushButton.setObjectName(u"thursday_pushButton")
        self.thursday_pushButton.setGeometry(QRect(430, 135, 40, 40))
        self.thursday_pushButton.setFont(font1)
        self.friday_pushButton = QPushButton(self.Settings_Manager_page)
        self.friday_pushButton.setObjectName(u"friday_pushButton")
        self.friday_pushButton.setGeometry(QRect(475, 135, 40, 40))
        self.friday_pushButton.setFont(font1)
        self.saturday_pushButton = QPushButton(self.Settings_Manager_page)
        self.saturday_pushButton.setObjectName(u"saturday_pushButton")
        self.saturday_pushButton.setGeometry(QRect(520, 135, 40, 40))
        self.saturday_pushButton.setFont(font1)
        self.sunday_pushButton = QPushButton(self.Settings_Manager_page)
        self.sunday_pushButton.setObjectName(u"sunday_pushButton")
        self.sunday_pushButton.setGeometry(QRect(565, 135, 40, 40))
        self.sunday_pushButton.setFont(font1)
        self.shield_1_label = QLabel(self.Settings_Manager_page)
        self.shield_1_label.setObjectName(u"shield_1_label")
        self.shield_1_label.setGeometry(QRect(410, 80, 40, 50))
        self.user_setpoint_pushButton = QPushButton(self.Settings_Manager_page)
        self.user_setpoint_pushButton.setObjectName(u"user_setpoint_pushButton")
        self.user_setpoint_pushButton.setGeometry(QRect(460, 90, 141, 31))
        self.user_setpoint_pushButton.setFont(font1)
        self.label_36 = QLabel(self.Settings_Manager_page)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 180, 171, 21))
        self.label_36.setFont(font3)
        self.label_37 = QLabel(self.Settings_Manager_page)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 200, 601, 31))
        self.label_37.setFont(font1)
        self.label_38 = QLabel(self.Settings_Manager_page)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 230, 40, 35))
        self.label_39 = QLabel(self.Settings_Manager_page)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 270, 40, 35))
        self.label_40 = QLabel(self.Settings_Manager_page)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 310, 40, 35))
        self.label_41 = QLabel(self.Settings_Manager_page)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 350, 40, 35))
        self.label_42 = QLabel(self.Settings_Manager_page)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 400, 40, 35))
        self.label_59 = QLabel(self.Settings_Manager_page)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 440, 40, 35))
        self.line_7 = QFrame(self.Settings_Manager_page)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 390, 601, 2))
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.label_60 = QLabel(self.Settings_Manager_page)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(50, 230, 100, 35))
        self.label_60.setFont(font1)
        self.label_61 = QLabel(self.Settings_Manager_page)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(50, 270, 100, 35))
        self.label_61.setFont(font1)
        self.label_62 = QLabel(self.Settings_Manager_page)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(50, 310, 100, 35))
        self.label_62.setFont(font1)
        self.label_63 = QLabel(self.Settings_Manager_page)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(50, 350, 100, 35))
        self.label_63.setFont(font1)
        self.shield_3_label = QLabel(self.Settings_Manager_page)
        self.shield_3_label.setObjectName(u"shield_3_label")
        self.shield_3_label.setGeometry(QRect(170, 230, 40, 35))
        self.shield_4_label = QLabel(self.Settings_Manager_page)
        self.shield_4_label.setObjectName(u"shield_4_label")
        self.shield_4_label.setGeometry(QRect(170, 270, 40, 35))
        self.shield_5_label = QLabel(self.Settings_Manager_page)
        self.shield_5_label.setObjectName(u"shield_5_label")
        self.shield_5_label.setGeometry(QRect(170, 310, 40, 35))
        self.shield_6_label = QLabel(self.Settings_Manager_page)
        self.shield_6_label.setObjectName(u"shield_6_label")
        self.shield_6_label.setGeometry(QRect(170, 350, 40, 35))
        self.morning_1_pushButton = QPushButton(self.Settings_Manager_page)
        self.morning_1_pushButton.setObjectName(u"morning_1_pushButton")
        self.morning_1_pushButton.setGeometry(QRect(220, 230, 91, 35))
        self.morning_1_pushButton.setFont(font1)
        self.morning_2_pushButton = QPushButton(self.Settings_Manager_page)
        self.morning_2_pushButton.setObjectName(u"morning_2_pushButton")
        self.morning_2_pushButton.setGeometry(QRect(320, 230, 91, 35))
        self.morning_2_pushButton.setFont(font1)
        self.morning_3_pushButton = QPushButton(self.Settings_Manager_page)
        self.morning_3_pushButton.setObjectName(u"morning_3_pushButton")
        self.morning_3_pushButton.setGeometry(QRect(420, 230, 91, 35))
        self.morning_3_pushButton.setFont(font1)
        self.morning_4_pushButton = QPushButton(self.Settings_Manager_page)
        self.morning_4_pushButton.setObjectName(u"morning_4_pushButton")
        self.morning_4_pushButton.setGeometry(QRect(520, 230, 91, 35))
        self.morning_4_pushButton.setFont(font1)
        self.day_1_pushButton = QPushButton(self.Settings_Manager_page)
        self.day_1_pushButton.setObjectName(u"day_1_pushButton")
        self.day_1_pushButton.setGeometry(QRect(220, 270, 91, 35))
        self.day_1_pushButton.setFont(font1)
        self.day_2_pushButton = QPushButton(self.Settings_Manager_page)
        self.day_2_pushButton.setObjectName(u"day_2_pushButton")
        self.day_2_pushButton.setGeometry(QRect(320, 270, 91, 35))
        self.day_2_pushButton.setFont(font1)
        self.day_3_pushButton = QPushButton(self.Settings_Manager_page)
        self.day_3_pushButton.setObjectName(u"day_3_pushButton")
        self.day_3_pushButton.setGeometry(QRect(420, 270, 91, 35))
        self.day_3_pushButton.setFont(font1)
        self.day_4_pushButton = QPushButton(self.Settings_Manager_page)
        self.day_4_pushButton.setObjectName(u"day_4_pushButton")
        self.day_4_pushButton.setGeometry(QRect(520, 270, 91, 35))
        self.day_4_pushButton.setFont(font1)
        self.evening_1_pushButton = QPushButton(self.Settings_Manager_page)
        self.evening_1_pushButton.setObjectName(u"evening_1_pushButton")
        self.evening_1_pushButton.setGeometry(QRect(220, 310, 91, 35))
        self.evening_1_pushButton.setFont(font1)
        self.evening_2_pushButton = QPushButton(self.Settings_Manager_page)
        self.evening_2_pushButton.setObjectName(u"evening_2_pushButton")
        self.evening_2_pushButton.setGeometry(QRect(320, 310, 91, 35))
        self.evening_2_pushButton.setFont(font1)
        self.evening_3_pushButton = QPushButton(self.Settings_Manager_page)
        self.evening_3_pushButton.setObjectName(u"evening_3_pushButton")
        self.evening_3_pushButton.setGeometry(QRect(420, 310, 91, 35))
        self.evening_3_pushButton.setFont(font1)
        self.evening_4_pushButton = QPushButton(self.Settings_Manager_page)
        self.evening_4_pushButton.setObjectName(u"evening_4_pushButton")
        self.evening_4_pushButton.setGeometry(QRect(520, 310, 91, 35))
        self.evening_4_pushButton.setFont(font1)
        self.night_4_pushButton = QPushButton(self.Settings_Manager_page)
        self.night_4_pushButton.setObjectName(u"night_4_pushButton")
        self.night_4_pushButton.setGeometry(QRect(520, 350, 91, 35))
        self.night_4_pushButton.setFont(font1)
        self.night_3_pushButton = QPushButton(self.Settings_Manager_page)
        self.night_3_pushButton.setObjectName(u"night_3_pushButton")
        self.night_3_pushButton.setGeometry(QRect(420, 350, 91, 35))
        self.night_3_pushButton.setFont(font1)
        self.night_2_pushButton = QPushButton(self.Settings_Manager_page)
        self.night_2_pushButton.setObjectName(u"night_2_pushButton")
        self.night_2_pushButton.setGeometry(QRect(320, 350, 91, 35))
        self.night_2_pushButton.setFont(font1)
        self.night_1_pushButton = QPushButton(self.Settings_Manager_page)
        self.night_1_pushButton.setObjectName(u"night_1_pushButton")
        self.night_1_pushButton.setGeometry(QRect(220, 350, 91, 35))
        self.night_1_pushButton.setFont(font1)
        self.label_68 = QLabel(self.Settings_Manager_page)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(50, 400, 561, 35))
        self.label_68.setFont(font1)
        self.label_69 = QLabel(self.Settings_Manager_page)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(50, 440, 561, 35))
        self.label_69.setFont(font1)
        self.settings_pages_stackedWidget.addWidget(self.Settings_Manager_page)
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.settings_pages_stackedWidget.addWidget(self.page_9)
        self.main_stackedWidget.addWidget(self.Settings_Main_page)

        self.retranslateUi(System_Station_Main_window)

        self.main_stackedWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(System_Station_Main_window)
    # setupUi

    def retranslateUi(self, System_Station_Main_window):
        System_Station_Main_window.setWindowTitle(QCoreApplication.translate("System_Station_Main_window", u"Form", None))
        self.label_12.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f", None))
        self.label_2.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0412\u044b\u0445\u043e\u0434:    0.00     \u0411\u0430\u0440", None))
        self.label.setText(QCoreApplication.translate("System_Station_Main_window", u"07/07/2024 21:44", None))
        self.go_to_main_settings_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438", None))
        self.label_8.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f", None))
        self.main_first_pushButton.setText("")
        self.label_10.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f", None))
        self.label_11.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f", None))
        self.label_3.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0417\u0430\u0434\u0430\u043d\u0438\u0435: 3.00     \u0411\u0430\u0440", None))
        self.label_6.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0412\u0445\u043e\u0434:      10.00    \u0411\u0430\u0440", None))
        self.label_9.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f", None))
        self.label_4.setText(QCoreApplication.translate("System_Station_Main_window", u"\u2206:              -10.00  \u0411\u0430\u0440", None))
        self.label_5.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0427\u0430\u0441\u0442\u043e\u0442\u0430:   0.0      Hz", None))
        self.label_7.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f", None))
        self.main_third_pushButton.setText("")
        self.main_second_pushButton.setText("")
        self.go_to_main_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0413\u043b\u0430\u0432\u043d\u044b\u0439 \u044d\u043a\u0440\u0430\u043d", None))
        self.go_to_main_page_label.setText("")
        self.go_to_manager_page_label.setText("")
        self.go_to_manager_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0449\u0438\u043a \n"
"\u0443\u0441\u0442\u0430\u0432\u043e\u043a", None))
        self.go_to_tracking_page_label.setText("")
        self.go_to_tracking_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041c\u043e\u043d\u0438\u0442\u043e\u0440\u0438\u043d\u0433", None))
        self.go_to_journal_page_label.setText("")
        self.go_to_journal_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0416\u0443\u0440\u043d\u0430\u043b", None))
        self.go_to_station_settings_page_label.setText("")
        self.go_to_station_settings_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438\n"
"\u0441\u0442\u0430\u043d\u0446\u0438\u0438", None))
        self.go_to_engineering_menu_page_label.setText("")
        self.go_to_engineering_menu_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0418\u043d\u0436\u0435\u043d\u0435\u0440\u043d\u043e\u0435 \n"
"\u043c\u0435\u043d\u044e", None))
        self.go_to_panel_settings_page_label.setText("")
        self.go_to_panel_settings_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438\n"
"\u043f\u0430\u043d\u0435\u043b\u0438", None))
        self.go_to_contacts_page_label.setText("")
        self.go_to_contacts_page_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b", None))
        self.label_21.setText("")
        self.label_22.setText("")
        self.label_23.setText("")
        self.label_24.setText("")
        self.label_25.setText("")
        self.label_26.setText("")
        self.label_27.setText(QCoreApplication.translate("System_Station_Main_window", u"08/07/2024 15:00   ", None))
        self.label_28.setText("")
        self.label_29.setText("")
        self.label_30.setText("")
        self.label_31.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0443\u0441\u0442\u0430\u0432\u043a\u0438", None))
        self.label_32.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0423\u0441\u0442\u0430\u0432\u043a\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f", None))
        self.label_33.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0434\u043d\u0435\u0439 \u043d\u0435\u0434\u0435\u043b\u0438", None))
        self.shield_2_label.setText("")
        self.monday_pushButton.setText("")
        self.tuesday_pushButton.setText("")
        self.wednesday_pushButton.setText("")
        self.thursday_pushButton.setText("")
        self.friday_pushButton.setText("")
        self.saturday_pushButton.setText("")
        self.sunday_pushButton.setText("")
        self.shield_1_label.setText("")
        self.user_setpoint_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00                 \u0411\u0430\u0440", None))
        self.label_36.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0449\u0438\u043a", None))
        self.label_37.setText(QCoreApplication.translate("System_Station_Main_window", u"          \u0412\u0440\u0435\u043c\u044f \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430:          \u0411\u0443\u0434\u043d\u0438             \u0412\u044b\u0445\u043e\u0434\u043d\u044b\u0435 \u0423\u0441\u0442\u0430\u0432\u043a\u0430:\u0411\u0443\u0434\u043d\u0438   \u0412\u044b\u0445\u043e\u0434\u043d\u044b\u0435", None))
        self.label_38.setText("")
        self.label_39.setText("")
        self.label_40.setText("")
        self.label_41.setText("")
        self.label_42.setText("")
        self.label_59.setText("")
        self.label_60.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0423\u0442\u0440\u043e", None))
        self.label_61.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0414\u0435\u043d\u044c", None))
        self.label_62.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0412\u0435\u0447\u0435\u0440", None))
        self.label_63.setText(QCoreApplication.translate("System_Station_Main_window", u"\u041d\u043e\u0447\u044c", None))
        self.shield_3_label.setText("")
        self.shield_4_label.setText("")
        self.shield_5_label.setText("")
        self.shield_6_label.setText("")
        self.morning_1_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"05    :    00", None))
        self.morning_2_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"05    :    00", None))
        self.morning_3_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.morning_4_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.day_1_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"10    :    00", None))
        self.day_2_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"00    :    00", None))
        self.day_3_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.day_4_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.evening_1_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"17    :    00", None))
        self.evening_2_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"17    :    00", None))
        self.evening_3_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.evening_4_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.night_4_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.night_3_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"3.00     \u0411\u0430\u0440", None))
        self.night_2_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"22    :    00", None))
        self.night_1_pushButton.setText(QCoreApplication.translate("System_Station_Main_window", u"22    :    00", None))
        self.label_68.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0434\u0435\u043d\u044c \u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a                      \u0422\u0438\u043f \u0434\u043d\u044f \u041d\u0435\u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d", None))
        self.label_69.setText(QCoreApplication.translate("System_Station_Main_window", u"\u0422\u0438\u043f \u0443\u0441\u0442\u0430\u0432\u043a\u0438 \u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c                          \u0422\u0435\u043a\u0443\u0449\u0430\u044f \u0443\u0441\u0442\u0430\u0432\u043a\u0430 3.00   \u0411\u0430\u0440", None))
    # retranslateUi

